### ISSUE TITLE
Table - get all rows

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/masquerade#14]
For example we need to check number of rows in a table after applying a filter.

Existing method:
ElementsCollection getRows(By rowBy);
does not have "empty" selector.

**Comment by jreznot** [comment]
It seems that we should provide EMPTY Condition for Table itself.
```
table.shouldBe(EMPTY)
```

**Comment by alexbudarov** [comment]
By empty I meant:
get all rows = get rows with no additional conditions

**Comment by jreznot** [comment]
In this case ALL By would be clearer
