### ISSUE TITLE
Tutorial: How to use input fields

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/masquerade#15]
LookupField, TextField, PickerField, DateField, DateTimeField

1. Input data
2. Assertions

**Comment by natfirst** [comment]
https://github.com/cuba-platform/masquerade/wiki/How-to-use-input-fields

**Comment by jreznot** [comment]
Review:

- Sort sections as follows: TextField, DateField, DateTimeField, LookupField, PickerField
- Show real examples that could be copy-pasted without <placeholders>
- Apply java code highlighting for code blocks and use `;` symbol
- Use HasActions constants with PickerField instead of string literal
- Do not start a sentence with "To ...".

Phrases:
> Sometimes it is needed to check, that
Sometimes we need to check if

> select the necessary value
select the desired value

Improvements:
- Mention standard conditions with examples before all the components
- Add small screenshots with components from Sampler and links to the latest cuba documentation

**Comment by jreznot** [comment]
Also, let's add CheckBox usage as first component

**Comment by natfirst** [comment]
https://github.com/cuba-platform/masquerade/wiki/How-to-use-input-fields

**Comment by jreznot** [comment]
Replace `byCubaId(<cubaId>)` with some test String ids. `byCubaId` is not required in case of cuba-id.

**Comment by jreznot** [comment]
> Click the lookup button to set the value to the PickerField

Replace with PickerField API:
```
pickerField.triggerAction(HasActions.OPEN)
```

**Comment by jreznot** [comment]
Fix code alignment of code block, the second line has inconsistent left margin

**Comment by jreznot** [comment]
Write this on single line:
```
_$(CheckBox, byCubaId(<cubaId>))
              .checked = true;
```

**Comment by jreznot** [comment]
Show Java examplse, do not use Groovy property syntax and tricks

**Comment by jreznot** [comment]
We should be able to copy and paste valid code to Java project and see no compilation warnings

**Comment by natfirst** [comment]
https://github.com/cuba-platform/masquerade/wiki/How-to-use-input-fields

**Comment by jreznot** [comment]
> The value passed to the method must have the following format: DDMMYYYY:

It is not true, depends on locale

**Comment by natfirst** [comment]
Fixed: https://github.com/cuba-platform/masquerade/wiki/How-to-use-input-fields
