### ISSUE TITLE
Support GroupTable component

### ISSUE THREAD

**Issue by feathergrass** [cuba-platform/masquerade#16]
- Expand / Collapse a node (selected by label).
- Get a collection of inner rows for further assertions.

### Updates

New component `GroupTable` is introduced.

It supports the following two conditions:

- `Conditions#EXPANDED` - checks that all group rows are expanded
- `Conditions#COLLAPSED` - checks that all group rows are collapsed

The `GroupTable` component has the following method:

- `expandAll()` - expands all group rows
- `collapseAll()` - collapses all group rows
- `expand(By groupRowSelector)` - expands first met group row that matches passed selector
- `collapse(By groupRowSelector)` - collapses first met group row that matches passed selector

### Usage example

```Groovy
@Test
void testExpandAll() {
    $c(AppMenu)
            .openItem(Menus.PRODUCT_BROWSE)

    $c(GroupTable, 'productsTable')
            .shouldBe(Condition.visible)
            .expandAll()
            .shouldBe(Conditions.EXPANDED)
}

@Test
void testCollapseAll() {
    $c(AppMenu)
            .openItem(Menus.PRODUCT_BROWSE)

    $c(GroupTable, 'productsTable')
            .shouldBe(Condition.visible)
            .collapseAll()
            .shouldBe(Conditions.COLLAPSED)
}

@Test
void testExpandSpecified() {
    $c(AppMenu)
            .openItem(Menus.PRODUCT_BROWSE)

    // only two groups exist
    $c(GroupTable, 'productsTable')
            .expand(withText('123'))
            .expand(withText('321'))
            .shouldBe(Conditions.EXPANDED)
}
```

**Comment by natfirst** [comment]
`expandAll()` method does not expand all groups, only the first one in the table
![mruifJCBK1](https://user-images.githubusercontent.com/17950251/70605485-0bbbc480-1c14-11ea-8aad-3b7a75d3c6ce.gif)
`collapseAll()` does nothing

**Comment by natfirst** [comment]
The second part of the issue will be implemented in another issue https://github.com/cuba-platform/masquerade/issues/66

**Comment by natfirst** [comment]
Also? add an ability to expand only one selected group
