### ISSUE TITLE
LookupField setValue() doesn't work properly with multiple spaces in a row

### ISSUE THREAD

**Issue by MTokarenko** [cuba-platform/masquerade#28]
It doesn't works because the popupContent component replace multi spaces into the one, and the input data to be choosen in the LookupField should has same input value and displayed in the popup component value.

**Comment by MTokarenko** [comment]
To clarify adding the attachement
![image](https://user-images.githubusercontent.com/24490395/38775484-a30106a0-4094-11e8-8b12-c642f5370773.png)

**Comment by dtsaryov** [comment]
The problem is related to CUBA itself. Filed an issue: cuba-platform/cuba#2550
