### ISSUE TITLE
Tutorial: Tables

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/masquerade#39]
* Rows selection (single and multi-select)
* Sorting
* Data asserting (cells checking)

**Comment by natfirst** [comment]
https://github.com/cuba-platform/masquerade/wiki/How-to-work-with-tables

**Comment by jreznot** [comment]
Let's show some real life examples with Table in UserBrowse screen:

- Find row by cell and check other cells
- Select multiple rows

> you may open

 you can open

**Comment by natfirst** [comment]
The `Examples` section were added https://github.com/cuba-platform/masquerade/wiki/How-to-work-with-tables
