### ISSUE TITLE
Problem with AppMenu component

### ISSUE THREAD

**Issue by GurtAlex** [cuba-platform/masquerade#41]
Sometimes main menu does not open after the first click on first menu item element with 'path[0]' and we see error e.g. like this:
`Element not found {By.chained({By.xpath: //span[contains(@class, 'v-menubar-menuitem') and @cuba-id="taxi$CustomerAccount.browse"],By.className: v-menubar-menuitem-caption})}
Expected: visible`

Chrome version:  67.0.3396.87

**Comment by dtsaryov** [comment]
The problem is not reproduced with the latest version
