### ISSUE TITLE
setValue(String value) method in TextField component sometimes doesn't work

### ISSUE THREAD

**Issue by GurtAlex** [cuba-platform/masquerade#49]
Sometimes first letter/-s isn't filled. See screenshot
![image](https://user-images.githubusercontent.com/2259726/44210619-06fa1400-a178-11e8-9d14-3ae8130d086b.png)

**Comment by dtsaryov** [comment]
Hello @GurtAlex 

Could you share more details about the problem? What version of masquerade is used? What browser (driver) and its version is used?
