### ISSUE TITLE
For modal windows .byCubaId() should exclude finding elements inside "v-window-modalitycurtain" div?

### ISSUE THREAD

**Issue by wrover** [cuba-platform/masquerade#50]
An error occurs when both parent and modal window have elements with the same cuba-id (typically windowCommit)

**Comment by jreznot** [comment]
We are not planning to handle modality curtain.

Use chained paths with windowId, like `_$("idofwindow", "idofcomponent")` or annotate your Composite with `@Wire("idofwindow")` and you will be able to work with multiple windows. It works for layouts too.

**Comment by jreznot** [comment]
By the way, please use https://www.cuba-platform.com/discuss/ for questions and discussions. GitHub is really bad for this.

**Comment by wrover** [comment]
Thanks for a quick reply. I think it would be better to add this to Wiki since it's quite common. I'll try later on.
Also as WA with multiple cuba-id="windowCommit" buttons for this particular situation sending Ctrl+Enter works well: `.sendKeys(Keys.chord(Keys.CONTROL, Keys.ENTER))`
