### ISSUE TITLE
Table.selectRow() opens maxTextLength area instead of selecting row

### ISSUE THREAD

**Issue by feathergrass** [cuba-platform/masquerade#54]
**Environment**
Masquerade version: 1.0-SNAPSHOT
Cuba version: 6.8.3

**Precondition**
Table has maxTextLength column.
![image](https://user-images.githubusercontent.com/29942318/49583060-6de24980-f970-11e8-8637-87f59f77f89b.png)

**Actual result**
Table.selectRow(byText("Not a text of maxLength cell")) does not select the row but clicks on the maxLength cell and opens the area with the full text.

**Expected result**
The row selected.

**Comment by dtsaryov** [comment]
Everything works ok with the latest version
