### ISSUE TITLE
Update selenide to 5.5.1

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/masquerade#67]
### Environment

- Masquerade version: 2.1

### Description of the bug or enhancement

New selenide version is available ([5.5.1](https://mvnrepository.com/artifact/com.codeborne/selenide/5.5.1))

**Comment by jreznot** [comment]
Selenide 5.8 released https://selenide.org/2020/02/28/selenide-5.8.0/

**Comment by natfirst** [comment]
Selenide 5.13 released https://selenide.org/2020/07/08/selenide-5.13.0/

**Comment by dtsaryov** [comment]
>  Update selenide to 5.5.1 #67 

But updated to 5.13 ;)
